create table Book(
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     person_id int REFERENCES person(id) ON DELETE CASCADE,
                     name varchar(100) NOT NULL,
                     author varchar(150) NOT NULL,
                     year int NOT NULL
);
create table Person(
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name varchar(100) NOT NULL UNIQUE,
                     birthdate int NOT NULL
)